// nodeJsBasic/angularfeatures/project1/src/app/demo1.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-demo1',
  template: `
   <div>
   
   <p>
    In this demo, we will show simple data bindings.
    
   </p>
         <h1>Basic data bindings and events</h1>
	    <div  class="alert alert-primary">
	      This is a message to show : {{message}}
	    </div>

         <h1>Event and Input</h1>
	    <div  class="alert alert-primary">
	      This is a message to show : {{message}}, counter = {{counter}}, 
	      current input = {{currentInput}}, 
	    </div>
	    
	    <div class="m-1">
	    Number to add to a counter : <input #testInput placeholder="123" value="10" />
	    
	    <a 	href="https://angular.io/guide/template-reference-variables"
	        target="_blank"
			class="link-info m-1">ℹ️ Learn more about 'Template reference variables'</a>
	    </div>


	    <div  class="alert alert-primary">
	      counter = {{counter}}, 
	      Added amount : {{currentInput}}, 
	    </div>
	    

	    <button [class]="'btn btn-primary'" (click)="addCounter(testInput.value)" >Add counter</button>
	    
	   <a 	href="https://angular.io/guide/event-binding"
		    target="_blank"
			class="link-info m-1">ℹ️ Learn more about 'Event bindings'</a>


    </div>
  `,
  styles: [
    `
    
    `
  ]
})
export class Demo1Component implements OnInit {
  message: String = 'Hello !!! How are you?';

  counter = 0;
  
  currentInput: string|number = '-';
  
  constructor() { }

  ngOnInit(): void {
  }
  
  addCounter(v: string) {
	var v2 : number = parseInt(v);
	this.currentInput = v2;
	this.counter = this.counter? this.counter : 0; // eliminate NaN
	this.counter+=v2;
  }
}

// nodeJsBasic/reactJs/my-app/src/Demo1.js
import React, { useState } from 'react';
  
function Demo2(props) {
  
  const [counter, setCounter] = useState(0);
  const handleClick = (e) => {
    // alert("The value of counter is " + counter)
    setCounter(counter + 1);
  }
  console.log('props', props);
  
  return (
    <div>
    	<p>Let's learn to write a basic component.</p>
        <h1>Features</h1>
        
        <ul>
          <li>Data binding (display data on pages)</li>
          <li>Receiving input from the parent component</li>
          <li>Event management (on click)</li>
          <li>Using states</li>
        </ul>
        
        <h1>Receiving input from the parent component</h1>
		<p>Hello there, </p>
		
		<div  class="alert alert-primary">
			{ JSON.stringify(props.inputFromParent) } 
		</div>
		
		
		<p>(this is the input from the parent component App.js) </p>
		
		<h1>Using events and states</h1>
		 
		<p>This component has a 'counter' state, initially 0. 
		Each time, you click on the button, the counter will increase by 1.
		The current counter value (state) is updated automatically.
		</p>  
		
		    
  		<p>Current counter value : {counter}</p>
        
        <button onClick={handleClick}
           class="btn btn-primary"
        >Click me!</button>
      
      <div class="my-2"></div>
      
      
        		  <a 	href="https://github.com/prawinn555/basictuto/blob/main/nodeJsBasic/reactJs/my-app/src/Demo1.js"
				        target="_blank"
						class="link-info m-1">🌐 Code of this demo</a>
						
    </div>
  );
}

export default Demo2;
